server:
  port: 8082

spring:
  application:
    name: service-c-analytics
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:swiftpay_analytics}
    username: ${DB_USER:swiftpay}
    password: ${DB_PASS:swiftpay}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: analytics
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: analytics
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      enable-auto-commit: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

swiftpay:
  kafka:
    topics:
      payment-completed: payment.completed

logging:
  level:
    com.swiftpay: INFO
    org.springframework.kafka: WARN
